name: tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ubuntu_test:
    runs-on: ubuntu-latest
    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1.0.0
        with:
          command: " "
      - name: version_test
        uses: asdf-vm/actions/plugin-test@v1.0.0
        with:
          command: "op --version"

  macos_test:
    runs-on: macos-latest
    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1.0.0
        with:
          command: " "
      - name: version_test
        uses: asdf-vm/actions/plugin-test@v1.0.0
        with:
          command: "op --version"

